export const firms = [
  { name: 'Evercore', office: 'New York', competitiveness: 9.8, tier: 'Elite Boutique' },
  { name: 'PJT Partners', office: 'New York', competitiveness: 9.7, tier: 'Elite Boutique' },
  { name: 'Centerview Partners', office: 'New York', competitiveness: 9.7, tier: 'Elite Boutique' },
  { name: 'Lazard', office: 'New York', competitiveness: 9.5, tier: 'Elite Boutique' },
  { name: 'Moelis', office: 'New York', competitiveness: 9.4, tier: 'Elite Boutique' },
  { name: 'Perella Weinberg', office: 'New York', competitiveness: 9.2, tier: 'Elite Boutique' },
  { name: 'Goldman Sachs', office: 'New York', competitiveness: 9.6, tier: 'Bulge Bracket' },
  { name: 'Morgan Stanley', office: 'New York', competitiveness: 9.5, tier: 'Bulge Bracket' },
  { name: 'J.P. Morgan', office: 'New York', competitiveness: 9.3, tier: 'Bulge Bracket' },
  { name: 'Bank of America', office: 'Charlotte', competitiveness: 8.8, tier: 'Bulge Bracket' },
  { name: 'Citi', office: 'New York', competitiveness: 8.9, tier: 'Bulge Bracket' },
  { name: 'Barclays', office: 'New York', competitiveness: 8.7, tier: 'Bulge Bracket' },
  { name: 'UBS', office: 'New York', competitiveness: 8.5, tier: 'Bulge Bracket' },
  { name: 'Jefferies', office: 'New York', competitiveness: 8.4, tier: 'Middle Market' },
  { name: 'Houlihan Lokey', office: 'Los Angeles', competitiveness: 8.3, tier: 'Middle Market' },
  { name: 'William Blair', office: 'Chicago', competitiveness: 7.9, tier: 'Middle Market' },
  { name: 'Stifel', office: 'Baltimore', competitiveness: 7.4, tier: 'Middle Market' },
  { name: 'Piper Sandler', office: 'Minneapolis', competitiveness: 7.2, tier: 'Middle Market' },
  { name: 'Baird', office: 'Milwaukee', competitiveness: 7.0, tier: 'Middle Market' },
  { name: 'RBC Capital Markets', office: 'New York', competitiveness: 8.1, tier: 'Middle Market' },
  { name: 'Lincoln International', office: 'Chicago', competitiveness: 7.6, tier: 'Middle Market' },
  { name: 'Harris Williams', office: 'Richmond', competitiveness: 7.5, tier: 'Regional Boutique' },
  { name: 'Raymond James', office: 'Atlanta', competitiveness: 6.8, tier: 'Regional Boutique' },
  { name: 'D.A. Davidson', office: 'Portland', competitiveness: 6.4, tier: 'Regional Boutique' },
  { name: 'Stephens', office: 'Little Rock', competitiveness: 6.2, tier: 'Regional Boutique' }
];
